name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  checks:
    name: Run checks
    runs-on: self-hosted-arc
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - name: Install depdendencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
      - name: Install Rust toolchain
        run: |
            rustup show
            rustup component add rustfmt clippy
      - name: Code format check
        run: cargo fmt -- --check
      - name: Unit tests
        run: cargo test --all
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Clean up
        if: always()
        run: cargo clean